class UiLocators:
    todo_input = ".new-todo"
    todo_list = "ul.todo-list li"
    todo_label = ".todo-list li label"
    todo_toggle = ".todo-list li .toggle"
    clear_complete = ".clear-completed"
    complete = ".completed"
    edit = "//div[@class='view']//input[@id='todo-input']"
    todo_label_text = "//label[text()="
    todo_xsibling = "]/preceding-sibling::input"
    todo_button_text = "//button[text()="
    todo_xancestor = "]/ancestor::li"
    todo_button_xsibling = "]/following-sibling::button"
    todo_text = ".todo-list li label:has-text("
    todo_destroy = ")+.destroy"
    checkall = "//input[@class='toggle-all']"
    todo_count = "//span[@class='todo-count']"
